feat(modules/addon-irsa): add variable assume policy
lablabs/terraform-aws-eks-universal-addon pull request #2
Opened 2024-07-31 07:41 UTC by katapultcloud

# Description
We need to have a more dynamic trust policy where we can define multiple condition values as well as different condition tests.

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [x] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?

2024-07-31 09:17 UTC, jaygridley requested changes

2024-07-31 09:17 UTC, jaygridley commented on modules/addon-irsa/variables.tf
> +variable "irsa_assume_role_policy_additional_condition_values" {
```suggestion
variable "irsa_assume_role_policy_condition_additional_values" {
```

2024-07-31 09:17 UTC, jaygridley commented on modules/addon-irsa/iam.tf
> +          "system:serviceaccount:${var.service_account_namespace}:${var.service_account_name}",
For the use-case you need, does it make sense to keep the original value? I am thinking to rework this to have something like
```
values = coalesce(var.irsa_assume_role_policy_condition_values, ["system:serviceaccount:${var.service_account_namespace}:${var.service_account_name}"])

variable "irsa_assume_role_policy_condition_values" {
  type = list(string)
  default = []
}
```

2024-07-31 13:30 UTC, katapultcloud commented on modules/addon-irsa/iam.tf
> +          "system:serviceaccount:${var.service_account_namespace}:${var.service_account_name}",
implemented

2024-07-31 13:31 UTC, katapultcloud commented on modules/addon-irsa/variables.tf
> +variable "irsa_assume_role_policy_additional_condition_values" {
not needed with the current coalesce feature

2024-07-31 15:43 UTC, jaygridley requested changes

2024-07-31 15:43 UTC, jaygridley commented on modules/addon-irsa/variables.tf
> +  default     = ""
null is there by intention, see https://github.com/lablabs/terraform-aws-eks-universal-addon/blob/22170ef16dedb2a8a6bd2e0945ded3c17002d2f4/addon-irsa.tf#L14

2024-07-31 15:43 UTC, jaygridley commented on modules/addon-irsa/variables.tf
> +  default     = ""
what issue does it cause?

2024-07-31 15:51 UTC, katapultcloud commented on modules/addon-irsa/variables.tf
> +  default     = ""
oh I didn't notice the additional logic. I ran into an issue where a null value cannot be a part of constructing a string in this definition:

```
      values = coalesce(var.irsa_assume_role_policy_condition_values, ["system:serviceaccount:${var.service_account_namespace}:${var.service_account_name}"])
```

I can add try statements to safetly handle null values in case service_account_* vars are null? Is there a better way to handle this?

2024-08-01 05:58 UTC, jaygridley commented on modules/addon-irsa/variables.tf
> +  default     = ""
Well, ok. Yeah, we can redo this using either `try` or some ternary

2024-08-01 11:59 UTC, katapultcloud commented on modules/addon-irsa/variables.tf
> +  default     = ""
I came up with this

```
  irsa_assume_role_policy_condition_values_default = [
    format("system:serviceaccount:%s:%s", var.service_account_namespace != null ? var.service_account_namespace : "", var.service_account_name != null ? var.service_account_name : "")
  ]
```

2024-08-02 11:37 UTC, jaygridley requested changes

2024-08-02 11:37 UTC, jaygridley commented on modules/addon-irsa/variables.tf
> +  description = "Specifies the values for the assume role trust policy condition. Defaults to an empty list (`[]`). Each entry in this list must follow the required format `system:serviceaccount:$ser
The description is not precise. The default is not an empty list but a list with a single value given by `irsa_assume_role_policy_condition_values_default`.

2024-08-02 13:05 UTC, katapultcloud commented on modules/addon-irsa/variables.tf
> +  description = "Specifies the values for the assume role trust policy condition. Defaults to an empty list (`[]`). Each entry in this list must follow the required format `system:serviceaccount:$ser
updated description

2024-08-02 14:24 UTC, jaygridley approved these changes
LGTM

2024-08-02 14:28 UTC, merged